### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by anviar**
Simple Dockerfile to build and run project using Docker engine

### CODE REVIEW

**Comment by rain0r** [comment]
Thank you for the pull request! I'm happy to enhance `ampd` with Docker support and merge this PR.

Just one question. This line:

```
curl -fsSL https://deb.nodesource.com/setup_12.x | bash - \
```

Is this needed to install `node` in the container? According to [the docs](https://nodejs.org/de/docs/guides/nodejs-docker-webapp/) a `FROM node:14` should be sufficient. 

I'm not a big fan of `curl ... | bash` calls.

**Comment by anviar** [comment]
Yes, you absolutely right.

You can check my first version
https://github.com/rain0r/ampd/pull/142/commits/a2fc233da73a4134b8ae0686fb3d1f3830bd4813

But it not worked ) I think better solution will be build frontend at first, copy angularclient directory to builder-backend stage and then run mvn package without frontend build but with js-files bundling.

Something like that (I not  tested right now):

```
FROM node:lts as builder-frontend
WORKDIR /srv
COPY ./angularclient .
ENV DEBIAN_FRONTEND=noninteractive
RUN set -x \
    && npm install \
    && npm run ng build

FROM maven:3-jdk-11 as builder-backend
WORKDIR /srv
COPY . .
ENV DEBIAN_FRONTEND=noninteractive
COPY --from=builder-frontend /srv ./angularclient
RUN mvn package

FROM openjdk:11-jre-slim
WORKDIR /srv
COPY --from=builder-backend /srv/target/ampd-*jar ./ampd.jar
EXPOSE 8080

CMD ["java", "-jar", "ampd.jar"]
```

I'm sorry, but I not have experience with Maven. but by my experiments when I used `-Dnpm.skip` flag, all js files was lost. May be something should be improved in pom.xml. But I don't know how )

Anyway, you right. Frontend and backend builds must be separated.

**Comment by rain0r** [comment]
Why did you use `-Dskip.npm`? This skips the step that builds the frontend (it's meant for developers to save time...).

When you clone this repository and simply execute `mvn package`, this builds the frontend  automatically and also a `jar`-file under `target/` that you can run with `java -jar target/...`.

So I'm not sure if the 2 builds must be separated. If you have Maven and Node in your Docker Container, a simple call of `mvn package` should be enough. But I'm not very experienced with Docker so I can only help on the Maven/Node side.

**Comment by anviar** [comment]
If you can use prebuilt frontend some way, the suggested solution above will be much better. It's secure and docker-way.

Otherwise suggested PR is single option. `curl| bash` is official installation method from node.js team. It's work right now for me.

Up to your decision.

**Comment by rain0r** [comment]
Thanks for your contribution!

**Pull request merged**
